### PR TITLE
Changed Shared Fonts section to address why browser cache falls short

### PR DESCRIPTION
**Pull request by jakeleichtling**

### CODE REVIEW

**Comment by jakeleichtling** [comment]
@mkruisselbrink We're adopting a change review system. For future PRs, please wait on an LGTM before merging.

**Comment by jyasskin** [comment]
Well, if @mkruisselbrink read over it and thought it looked good, that's sufficient for my notion of the right review system.

**Comment by jakeleichtling** [comment]
My misunderstanding :). You're all good @mkruisselbrink. Revising the policy to "Don't merge your own PR without an LGTM from someone else."

**Comment by mkruisselbrink** [comment]
Also my mistake, I'll do better next time. My first time using github and pull requests...

**Pull request merged**
